name: HACS Validation

on:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

permissions:
    contents: read

jobs:
    validate:
        name: HASS and Hassfest Validation
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744"
            - name: HACS Action
              if: ${{ github.repository == 'pyalarmdotcom/alarmdotcom' || github.repository == 'dnnaji/alarmdotcom-ha-thermostat' }}
              uses: hacs/action@dcb30e72781db3f207d5236b861172774ab0b485
              with:
                  category: "integration"
            - name: Hassfest validation
              uses: "home-assistant/actions/hassfest@f6f29a7ee3fa0eccadf3620a7b9ee00ab54ec03b"
